### ISSUE TITLE
"Running" button does not change back to "Run Test" after test has finished running.

### ISSUE THREAD

**Issue by MilesWT** [MilesWT/USB-Benchmark#4]

**Comment by bdavs** [comment]
I can't replicate this bug.  Can you make sure that you are using the most up to date code. I made some changes recently that may have fixed this bug.

**Comment by MilesWT** [comment]
I'm up to date. It still never changes back to Run Test regardless of whether the results window is closed.

**Comment by bdavs** [comment]
Unable to replicate

**Comment by MilesWT** [comment]
Your commits weren't showing up on GitHub for whatever reason and pulling just said it was up to date. I've pulled successfully now and it's all fixed.
