### ISSUE TITLE
Trying to run with older generic USB drive crashes the program

### ISSUE THREAD

**Issue by MilesWT** [MilesWT/USB-Benchmark#5]
When trying to run it with an older generic USB drive, it crashes the program because it looks like WMIC cannot get some of the metadata values. So just a null check somewhere is likely what would fix this.
![image](https://cloud.githubusercontent.com/assets/11743094/25111874/a28f1546-23bb-11e7-9702-6ed3500836df.png)

**Comment by MilesWT** [comment]
Huh, I just tried it with this older flash drive again and I am unable to reproduce this bug.

**Comment by bdavs** [comment]
This error should be caught though. I will leave it up

**Comment by bdavs** [comment]
ba91e45be4f9ae87d9a8cd8f509989e55a8b0cc4
