### ISSUE TITLE
Multiple graphs in Results view

### ISSUE THREAD

**Issue by MilesWT** [MilesWT/USB-Benchmark#6]
Is this the intended result of running a test multiple times on the same drive, where the new graph keeps getting added to the existing?
![image](https://cloud.githubusercontent.com/assets/11743094/25112113/1d0dde14-23bd-11e7-81de-357fd930fd5e.png)
![image](https://cloud.githubusercontent.com/assets/11743094/25112226/eae27b42-23bd-11e7-95da-3b7845ce39e5.png)

I think there should be some way to clear all existing graphs or even individual graphs.

**Comment by bdavs** [comment]
This was fixed
