### ISSUE TITLE
Minor Enhancements for Results view

### ISSUE THREAD

**Issue by MilesWT** [MilesWT/USB-Benchmark#8]
- Free Space should be converted to MB
- Maybe add a time/date that the test was completed at at the top of the window.

![image](https://cloud.githubusercontent.com/assets/11743094/25112574/36805798-23c0-11e7-9d23-314a4c8a19cb.png)

**Comment by bdavs** [comment]
7060344a32c1c5ae5e94e72e5180cab81bf0de94
